# Generated by Django 5.1.4 on 2025-01-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.RemoveField(
            model_name='content',
            name='message_id',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='topic_in_category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='topic_in_category',
            name='topic_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='topic_in_category',
        ),
    ]
